DROP ALL OBJECTS;
CREATE TABLE IF NOT EXISTS FILMS (
    FILM_ID BIGINT NOT NULL AUTO_INCREMENT,
    FILM_NAME CHARACTER VARYING NOT NULL,
    DESCRIPTION CHARACTER VARYING,
    RELEASE_DATE DATE NOT NULL,
    DURATION INTEGER NOT NULL,
    MPA_ID BIGINT,
    CONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID)
);

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL CHARACTER VARYING NOT NULL,
    LOGIN CHARACTER VARYING,
    NAME CHARACTER VARYING,
    BIRTHDAY DATE NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS MPA (
    MPA_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRES (
    GENRE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME   VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
   FILM_ID BIGINT NOT NULL REFERENCES FILMS (FILM_ID),
   GENRE_ID BIGINT NOT NULL REFERENCES GENRES (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS LIKES (
    FILM_ID BIGINT NOT NULL REFERENCES FILMS (FILM_ID),
    USER_ID BIGINT NOT NULL REFERENCES USERS (USER_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDSHIPS (
    USER_ID BIGINT NOT NULL REFERENCES USERS (USER_ID),
    FRIEND_ID BIGINT NOT NULL REFERENCES USERS (USER_ID)
);